version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234567 
      POSTGRES_DB: dscatalog
    ports:
      - "5433:5432"  # Porta local:porta do container
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
